name: Publish Docker Image to DockerHub

on:
  push:
    tags:
      - 'v*'  # Asegura que solo se ejecute cuando se cree un tag como 'v3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Esta es la versi칩n m치s reciente de checkout

      # 2. Log in to DockerHub using secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2  # Actualizamos a la versi칩n m치s reciente de login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my_nginx_repo:${{ github.ref_name }} .

      # 4. Push the Docker image to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my_nginx_repo:${{ github.ref_name }}